const { supabase } = require('../config');
const { validateWalletAddress } = require('../middleware/verifyAdmin');
const { createNotification } = require('../services/notificationService');
const { getAuthUser, getStableWallet } = require('../middleware/identity');

const resolveActor = async (req) => {
  const authUser = await getAuthUser(req);
  if (authUser) {
    return { user: authUser, wallet: getStableWallet(req) || `user_${authUser.id}` };
  }
  const claimed = req.body?.userWallet;
  if (claimed && validateWalletAddress(claimed)) {
    const { data: legacyUser } = (await supabase
      .from('users')
      .select('*')
      .eq('wallet_address', claimed.toLowerCase())
      .single()) || {};
    return { user: legacyUser || null, wallet: claimed };
  }
  return null;
};

const getRetentionPolicies = async (req, res) => {
  try {
    const { data: policies, error } = (await supabase
      .from('retention_policies')
      .select('*')
      .eq('is_active', true)
      .order('created_at', { ascending: false })) || {};
    if (error) throw error;
    res.json({ success: true, policies });
  } catch (error) {
    console.error('Get retention policies error:', error);
    res.status(500).json({ error: 'Failed to get retention policies' });
  }
};

const createRetentionPolicy = async (req, res) => {
  try {
    const { name, caseType, retentionDays, archiveMethod, jurisdiction, lawReference } = req.body;
    const actor = await resolveActor(req);
    if (!actor) {
      return res.status(401).json({ error: 'Valid wallet address or authentication required' });
    }
    const { data: policy, error } = (await supabase
      .from('retention_policies')
      .insert({
        name,
        case_type: caseType,
        retention_days: retentionDays,
        archive_method: archiveMethod,
        jurisdiction,
        law_reference: lawReference,
        created_by: actor.wallet,
      })
      .select()
      .single()) || {};
    if (error) throw error;
    res.json({ success: true, policy });
  } catch (error) {
    console.error('Create retention policy error:', error);
    res.status(500).json({ error: 'Failed to create retention policy' });
  }
};

const exportTimelinePdf = async (req, res) => {
  try {
    const { caseId, evidence } = req.body;

    if (!Array.isArray(evidence) || evidence.length === 0) {
      return res.status(400).json({ error: 'Evidence must be a non-empty array.' });
    }

    const pdfContent = `CASE EVIDENCE TIMELINE REPORT\nCase ID: ${caseId}\nGenerated: ${new Date().toLocaleString()}\nTotal Evidence Items: ${evidence.length}\n\nEVIDENCE CHRONOLOGY:\n${evidence.map((item, i) => `${i + 1}. ${item.title}\n   Type: ${item.type}\n   Date: ${new Date(item.timestamp).toLocaleString()}\n   Submitted by: ${(item.submitted_by || 'unknown').substring(0, 8)}...\n   Hash: ${item.hash}\n`).join('')}\nGenerated by EVID-DGC Blockchain Evidence Management System.`;
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="timeline_${caseId}_${new Date().toISOString().split('T')[0]}.txt"`,
    );
    res.send(Buffer.from(pdfContent));
  } catch (error) {
    console.error('Timeline PDF export error:', error);
    res.status(500).json({ error: 'Failed to export timeline as PDF' });
  }
};

// Get evidence with expiry information
const getEvidenceExpiry = async (req, res) => {
  try {
    const { filter = 'all', wallet } = req.query;

    if (!validateWalletAddress(wallet)) {
      return res.status(403).json({ error: 'Unauthorized access: Invalid wallet address' });
    }

    // Verify user exists, is active, and has an authorized role
    const { data: user, error: userError } = (await supabase
      .from('users')
      .select('id, role, is_active')
      .eq('wallet_address', wallet.toLowerCase())
      .single()) || {};

    if (userError || !user || !user.is_active) {
      return res.status(403).json({ error: 'Unauthorized access' });
    }

    if (!['admin', 'investigator', 'evidence_manager', 'auditor'].includes(user.role)) {
      return res.status(403).json({ error: 'Unauthorized: Insufficient role' });
    }

    let query = supabase.from('evidence').select('*');

    const now = new Date();
    const thirtyDaysFromNow = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
    const sevenDaysFromNow = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

    switch (filter) {
      case 'expired':
        query = query.lt('expiry_date', now.toISOString()).eq('legal_hold', false);
        break;
      case '30days':
        query = query
          .lte('expiry_date', thirtyDaysFromNow.toISOString())
          .gte('expiry_date', now.toISOString());
        break;
      case '7days':
        query = query
          .lte('expiry_date', sevenDaysFromNow.toISOString())
          .gte('expiry_date', now.toISOString());
        break;
      case 'legal_hold':
        query = query.eq('legal_hold', true);
        break;
      case 'all':
        break;
      default:
        return res.status(400).json({ error: 'Invalid filter value' });
    }

    const { data: evidence, error } = await query.order('expiry_date', { ascending: true });
    if (error) throw error;

    res.json({ success: true, evidence });
  } catch (error) {
    console.error('Get evidence expiry error:', error);
    res.status(500).json({ error: 'Failed to get evidence expiry information' });
  }
};

// Set legal hold on evidence
const setLegalHold = async (req, res) => {
  try {
    const { id } = req.params;
    const { legalHold } = req.body;

    if (typeof legalHold !== 'boolean') {
      return res.status(400).json({ error: 'legalHold must be a boolean value' });
    }

    const actor = await resolveActor(req);
    if (!actor) {
      return res.status(401).json({ error: 'Valid wallet address or authentication required' });
    }

    const user = actor.user;
    if (!user) {
      return res.status(403).json({ error: 'User not found' });
    }

    if (!user.is_active) {
      return res.status(403).json({ error: 'User account is inactive' });
    }

    if (!['admin', 'investigator', 'evidence_manager'].includes(user.role)) {
      return res
        .status(403)
        .json({ error: 'Unauthorized: Insufficient role for legal hold operations' });
    }

    const { data: evidence, error: fetchError } = (await supabase
      .from('evidence')
      .select('id')
      .eq('id', id)
      .single()) || {};

    if (fetchError || !evidence) {
      return res.status(404).json({ error: 'Evidence not found' });
    }

    const { error } = (await supabase
      .from('evidence')
      .update({ legal_hold: legalHold })
      .eq('id', id)) || {};

    if (error) throw error;

    // Audit log (check returned error since Supabase does not throw on DB failures)
    const { error: auditLogError } = (await supabase.from('activity_logs').insert({
      user_id: actor.wallet,
      action: legalHold ? 'legal_hold_set' : 'legal_hold_removed',
      details: `Evidence ID: ${id}`,
      timestamp: new Date().toISOString(),
    })) || {};
    if (auditLogError) {
      console.error('Failed to log legal hold action:', auditLogError);
    }

    res.json({ success: true });
  } catch (error) {
    console.error('Set legal hold error:', error);
    res.status(500).json({ error: 'Failed to set legal hold' });
  }
};

// Apply retention policy to multiple evidence
const bulkRetentionPolicy = async (req, res) => {
  try {
    const { policyId, evidenceIds } = req.body;

    const actor = await resolveActor(req);
    if (!actor) {
      return res.status(401).json({ error: 'Valid wallet address or authentication required' });
    }

    const user = actor.user;
    if (!user || !user.is_active) {
      return res.status(403).json({ error: 'User not found or inactive' });
    }

    if (!['admin', 'investigator', 'evidence_manager'].includes(user.role)) {
      return res.status(403).json({ error: 'Unauthorized: Insufficient role for bulk operations' });
    }

    if (!evidenceIds || !Array.isArray(evidenceIds) || evidenceIds.length === 0) {
      return res.status(400).json({ error: 'Invalid or empty evidenceIds' });
    }

    if (!policyId) {
      return res.status(400).json({ error: 'policyId is required' });
    }

    const { data: policy, error: policyError } = (await supabase
      .from('retention_policies')
      .select('*')
      .eq('id', policyId)
      .single()) || {};

    if (policyError || !policy) {
      return res.status(404).json({ error: 'Retention policy not found' });
    }

    const expiryDate = new Date();
    expiryDate.setDate(expiryDate.getDate() + policy.retention_days);

    const { error, count } = (await supabase
      .from('evidence')
      .update(
        {
          retention_policy_id: policyId,
          expiry_date: expiryDate.toISOString(),
        },
        { count: 'exact' },
      )
      .in('id', evidenceIds)
      .select()) || {};

    if (error) throw error;

    // Audit log (check returned error since Supabase does not throw on DB failures)
    const { error: auditLogError } = (await supabase.from('activity_logs').insert({
      user_id: actor.wallet,
      action: 'bulk_retention_policy_applied',
      details: JSON.stringify({
        policy_id: policyId,
        evidence_ids: evidenceIds,
        affected_count: count || 0,
      }),
      timestamp: new Date().toISOString(),
    })) || {};
    if (auditLogError) {
      console.error('Failed to log bulk retention policy action:', auditLogError);
    }

    res.json({ success: true, updated: count || 0 });
  } catch (error) {
    console.error('Bulk retention policy error:', error);
    res.status(500).json({ error: 'Failed to apply retention policy' });
  }
};

// Update an existing retention policy
const updateRetentionPolicy = async (req, res) => {
  try {
    const { id } = req.params;
    const safeId = parseInt(id, 10);
    if (isNaN(safeId)) {
      return res.status(400).json({ error: 'Invalid policy ID' });
    }

    const {
      name, caseType, retentionDays, archiveMethod, jurisdiction, lawReference, isActive,
    } = req.body;

    const patch = {};
    if (name !== undefined) patch.name = name;
    if (caseType !== undefined) patch.case_type = caseType;
    if (retentionDays !== undefined) patch.retention_days = parseInt(retentionDays, 10);
    if (archiveMethod !== undefined) patch.archive_method = archiveMethod;
    if (jurisdiction !== undefined) patch.jurisdiction = jurisdiction;
    if (lawReference !== undefined) patch.law_reference = lawReference;
    if (isActive !== undefined) patch.is_active = Boolean(isActive);

    const { data: policy, error } = (await supabase
      .from('retention_policies')
      .update(patch)
      .eq('id', safeId)
      .select()
      .single()) || {};
    if (error) {
      if (error.code === 'PGRST116') {
        return res.status(404).json({ success: false, error: 'Retention policy not found' });
      }
      throw error;
    }

    const { error: logError } = (await supabase.from('activity_logs').insert({
      user_id: req.headers['x-user-wallet'] || req.authenticatedWallet || 'system',
      action: 'retention_policy_updated',
      details: JSON.stringify({ policy_id: safeId }),
      timestamp: new Date().toISOString(),
    })) || {};
    if (logError) console.error('Failed to log retention policy update:', logError);

    res.json({ success: true, policy });
  } catch (error) {
    console.error('Update retention policy error:', error);
    res.status(500).json({ success: false, error: 'Failed to update retention policy' });
  }
};

// Deactivate (soft delete) a retention policy
const deleteRetentionPolicy = async (req, res) => {
  try {
    const { id } = req.params;
    const safeId = parseInt(id, 10);
    if (isNaN(safeId)) {
      return res.status(400).json({ success: false, error: 'Invalid policy ID' });
    }

    const { data: policy, error } = (await supabase
      .from('retention_policies')
      .update({ is_active: false })
      .eq('id', safeId)
      .select()
      .single()) || {};
    if (error) {
      if (error.code === 'PGRST116') {
        return res.status(404).json({ success: false, error: 'Retention policy not found' });
      }
      throw error;
    }

    const { error: logError } = (await supabase.from('activity_logs').insert({
      user_id: req.headers['x-user-wallet'] || req.authenticatedWallet || 'system',
      action: 'retention_policy_deleted',
      details: JSON.stringify({ policy_id: safeId, name: policy.name }),
      timestamp: new Date().toISOString(),
    })) || {};
    if (logError) console.error('Failed to log retention policy delete:', logError);

    res.json({ success: true });
  } catch (error) {
    console.error('Delete retention policy error:', error);
    res.status(500).json({ success: false, error: 'Failed to delete retention policy' });
  }
};

// Evidence expiring within N days (legacy raw-array contract used across workstations)
const getEvidenceExpiring = async (req, res) => {
  try {
    const { days = 30 } = req.query;
    const daysNum = parseInt(days, 10);

    const now = new Date();
    const horizon = new Date(now.getTime() + (daysNum || 0) * 24 * 60 * 60 * 1000);

    let query = supabase
      .from('evidence')
      .select('id, title, file_name, case_id, expiry_date, retention_policy_id, submitted_by, legal_hold, archived, timestamp');

    if (daysNum > 0) {
      query = query
        .not('expiry_date', 'is', null)
        .lte('expiry_date', horizon.toISOString());
    }
    // days === 0 → everything with an expiry_date (incl. expired)

    const { data: rows, error } = (await query.order('expiry_date', { ascending: true }).limit(500)) || {};
    if (error) throw error;

    const data = (rows || []).map((row) => {
      const daysUntil = row.expiry_date
        ? Math.ceil((new Date(row.expiry_date) - now) / (24 * 60 * 60 * 1000))
        : null;
      return {
        id: row.id,
        title: row.title || row.file_name || `Evidence ${row.id}`,
        caseId: row.case_id || null,
        expiryDate: row.expiry_date,
        daysUntilExpiry: daysUntil,
        retentionPolicyId: row.retention_policy_id || null,
        submittedBy: row.submitted_by || null,
        legal_hold: Boolean(row.legal_hold),
        archived: Boolean(row.archived),
      };
    });

    res.json(data);
  } catch (error) {
    console.error('Get evidence expiring error:', error);
    res.status(500).json({ success: false, error: 'Failed to get expiring evidence' });
  }
};

// Archive evidence items (retention archive flow)
const archiveEvidence = async (req, res) => {
  try {
    const { evidenceIds, archiveLocation, archivedBy } = req.body;

    if (!Array.isArray(evidenceIds) || evidenceIds.length === 0) {
      return res.status(400).json({ success: false, error: 'evidenceIds must be a non-empty array' });
    }

    const { error, count } = (await supabase
      .from('evidence')
      .update({
        archived: true,
        archive_location: archiveLocation || 'Archive',
        archived_at: new Date().toISOString(),
        archived_by: archivedBy || req.headers['x-user-wallet'] || req.authenticatedWallet || 'system',
      }, { count: 'exact' })
      .in('id', evidenceIds)) || {};

    if (error) throw error;

    const updatedCount = count ?? 0;

    const { error: logError } = (await supabase.from('activity_logs').insert({
      user_id: req.headers['x-user-wallet'] || req.authenticatedWallet || 'system',
      action: 'evidence_archived',
      details: JSON.stringify({ evidence_ids: evidenceIds, location: archiveLocation || 'Archive' }),
      timestamp: new Date().toISOString(),
    })) || {};
    if (logError) console.error('Failed to log evidence archive:', logError);

    res.json({ success: true, updated: updatedCount });
  } catch (error) {
    console.error('Archive evidence error:', error);
    res.status(500).json({ success: false, error: 'Failed to archive evidence' });
  }
};

// Check for expiring evidence and send notifications
const checkExpiry = async (req, res) => {
  try {
    const { wallet } = req.query;

    if (!validateWalletAddress(wallet)) {
      return res.status(403).json({ error: 'Unauthorized access: Invalid wallet address' });
    }

    // Verify user exists, is active, and has an authorized role
    const { data: user, error: userError } = (await supabase
      .from('users')
      .select('id, role, is_active')
      .eq('wallet_address', wallet.toLowerCase())
      .single()) || {};

    if (userError || !user || !user.is_active) {
      return res.status(403).json({ error: 'Unauthorized access' });
    }

    if (!['admin', 'investigator', 'evidence_manager', 'auditor'].includes(user.role)) {
      return res.status(403).json({ error: 'Unauthorized: Insufficient role' });
    }

    const now = new Date();
    const thirtyDaysFromNow = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    let notificationsSent = 0;

    const { data: expiring30, error: error30 } = (await supabase
      .from('evidence')
      .select('*')
      .lte('expiry_date', thirtyDaysFromNow.toISOString())
      .gte('expiry_date', now.toISOString())
      .eq('legal_hold', false)) || {};

    if (error30) {
      console.error('Database error checking expiry:', error30);
      return res.status(500).json({ error: 'Failed to fetch expiring evidence' });
    }

    if (expiring30 && expiring30.length > 0) {
      const notificationPromises = expiring30.map((evidence) =>
        createNotification(
          evidence.submitted_by,
          'Evidence Expiry Warning',
          `Evidence "${evidence.title}" will expire in 30 days`,
          'system',
          { evidence_id: evidence.id, expiry_date: evidence.expiry_date },
        ),
      );

      const results = await Promise.allSettled(notificationPromises);
      notificationsSent = results.filter((r) => r.status === 'fulfilled' && r.value != null).length;
    }

    res.json({ success: true, notifications_sent: notificationsSent });
  } catch (error) {
    console.error('Check expiry error:', error);
    res.status(500).json({ error: 'Failed to check expiring evidence' });
  }
};

module.exports = {
  getRetentionPolicies,
  createRetentionPolicy,
  exportTimelinePdf,
  getEvidenceExpiry,
  setLegalHold,
  bulkRetentionPolicy,
  checkExpiry,
  updateRetentionPolicy,
  deleteRetentionPolicy,
  getEvidenceExpiring,
  archiveEvidence,
};
